# Generated by Django 5.1.7 on 2025-04-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='current_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='pay_term',
            field=models.IntegerField(default=12),
        ),
    ]
