# Generated by Django 5.1.7 on 2025-04-05 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust_rating', '0002_loan_current_payment_loan_interest_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='trust_rating',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='trust_rating.client'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='current_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='pay_term',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='trust_rating.loan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('On-time', 'On-time'), ('Late', 'Late'), ('Missed', 'Missed')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='client',
            table='trust_rating_client',
        ),
    ]
